--- #YAML:1.0
name:               App-repl
version:            0.126
abstract:           REPL with tabcompletion and perldoc support
author:
    - Magnus Woldrich <trapd00r@trapd00r.se>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    B::Keywords:          0
    Eval::WithLexicals:   0
    strictures:           0
    Term::ReadLine::Gnu:  0
resources:
    bugtracker:  https://github.com/trapd00r/re.pl/issues
    repository:  https://github.com/trapd00r/re.pl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
